ENVIRONMENT:
  MAX_EPISODE_STEPS: 1000

SIMULATOR:
  TYPE: "RearrangementSim-v0"
  TURN_ANGLE: 10
  TILT_ANGLE: 10
  INITIAL_LOOK_DOWN_ANGLE: 30
  ACTION_SPACE_CONFIG: "RearrangementActions-v0"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
    MAX_CLIMB: 0.1
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 90
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 90
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
  GRAB_DISTANCE: 1.0
  HABITAT_SIM_V0:
    ENABLE_PHYSICS: True

TASK:
  TYPE: RearrangementTask-v0
  POSSIBLE_ACTIONS: ["MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "GRAB_RELEASE"]
  SUCCESS_DISTANCE: 0.25

  SENSORS: ["GRIPPED_OBJECT_SENSOR", "ALL_OBJECT_POSITIONS", "ALL_OBJECT_GOALS", "ORACLE_NEXT_OBJECT_SENSOR", "RANDOM_OBJECT_SENSOR", "CLOSEST_OBJECT_SENSOR", "L2DIST_OBJECT_SENSOR"]
  # SENSORS: [""]
  GOAL_SENSOR_UUID: object_goal
  NEXT_OBJECT_SENSOR_UUID: random_object

  MEASUREMENTS: ['OBJECT_TO_GOAL_DISTANCE', 'AGENT_TO_OBJECT_DISTANCE', 'EPISODE_DISTANCE']
  SUCCESS:
    SUCCESS_DISTANCE: 0.25
  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS
  EOR_TOP_DOWN_MAP:
    MAP_RESOLUTION: 256


DATASET:
  TYPE: RearrangementDataset-v0
  SPLIT: train
  CONTENT_SCENES: ["*"]
  DATA_PATH: "data/datasets/rearrangement/gibson/v1/{split}/{split}.json.gz"
